
trigger:
- master

pr:
- master

jobs:
- job: Windows
  strategy:
    matrix:
      'VS2019 Release':
        configuration: Release
        generator: 'Visual Studio 16 2019'
      'VS2019 Debug':
        configuration: Debug
        generator: 'Visual Studio 16 2019'

  pool:
    name: 'default'
    demands:
    - Agent.OS -equals Windows_NT
    - cmake
    - VisualStudio_16.0

  steps:
  - task: CMake@1
    displayName: 'CMake Configure'
    inputs:
      cmakeArgs: '.. -G"$(generator)" -A"x64"'
  - task: CMake@1
    displayName: 'CMake Build'
    inputs:
      cmakeArgs: '--build . --config $(configuration)'

- job: Linux
  strategy:
    matrix:
      'GCC11 Release':
        cCompiler: gcc-11
        cxxCompiler: g++-11
        configuration: Release
        generator: 'Ninja'
      'Clang14 Debug':
        cCompiler: clang-14
        cxxCompiler: clang++-14
        configuration: Debug
        generator: 'Ninja'

  pool:
    name: 'default'
    demands:
    - Agent.OS -equals Linux
    - docker

  container: ghcr.io/unistuttgart-visus/megamol_ci_ubuntu:master

  steps:
  - task: CMake@1
    displayName: 'CMake Configure'
    inputs:
      cmakeArgs: '.. -G"$(generator)" -DCMAKE_C_COMPILER=$(cCompiler) -DCMAKE_CXX_COMPILER=$(cxxCompiler) -DCMAKE_BUILD_TYPE=$(configuration)'
  - task: CMake@1
    displayName: 'CMake Build'
    inputs:
      cmakeArgs: '--build .'
